@Kakeibo_HostAddress = http://localhost:7168

GET {{Kakeibo_HostAddress}}/api/getAllCategories

###

POST {{Kakeibo_HostAddress}}/api/addTransaction
Content-Type: application/json

{
  "categoryId": 1,
  "memo": "スーパーで買い物",
  "amount": 3500,
  "date": "2025-03-03T00:00:00Z"
}
###




GET {{Kakeibo_HostAddress}}/api/searchTransaction/1

###

PUT {{Kakeibo_HostAddress}}/api/updateTransaction
Content-Type: application/json

{
  "id": 1,
  "categoryId": 1,
  "memo": "京王ストアで買い物",
  "amount": 2000,
  "date": "2025-03-03T00:00:00Z"
}
###

DELETE {{Kakeibo_HostAddress}}/api/deleteTransaction/1

###

POST {{Kakeibo_HostAddress}}/api/createSubscriptions
Content-Type: application/json

{
  "name": "ネトフリ",
  "amount": 900
}
###

GET {{Kakeibo_HostAddress}}/api/getAllSubscriptions

###

PUT {{Kakeibo_HostAddress}}/api/updateSubscriptions
Content-Type: application/json
{
  "id": 1,
  "name": "ネトフリ",
  "amount": 900
}
###

DELETE {{Kakeibo_HostAddress}}/api/deleteSubscriptions/1

###

POST {{Kakeibo_HostAddress}}/api/registerSubscriptions

###
