// <auto-generated />
using System;
using Kakeibo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kakeibo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304065005_addSubscription")]
    partial class addSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kakeibo.Domain.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsIncome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Kakeibo.Domain.Entities.MonthlySummaryEntity", b =>
                {
                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gaishokuhi")
                        .HasColumnType("int");

                    b.Property<int>("Iryouhi")
                        .HasColumnType("int");

                    b.Property<int>("Kounetsuhi")
                        .HasColumnType("int");

                    b.Property<int>("Koutsuhi")
                        .HasColumnType("int");

                    b.Property<int>("Kyuryo")
                        .HasColumnType("int");

                    b.Property<int>("RinjiShunyu")
                        .HasColumnType("int");

                    b.Property<int>("Shokuhi")
                        .HasColumnType("int");

                    b.Property<int>("Shuusi")
                        .HasColumnType("int");

                    b.Property<int>("Sonota")
                        .HasColumnType("int");

                    b.Property<int>("Subscription")
                        .HasColumnType("int");

                    b.Property<int>("Suidouhi")
                        .HasColumnType("int");

                    b.Property<int>("Tsuusinhi")
                        .HasColumnType("int");

                    b.Property<int>("Yachin")
                        .HasColumnType("int");

                    b.Property<int>("Zeikin")
                        .HasColumnType("int");

                    b.HasKey("Month");

                    b.ToTable("MonthlySummaries");
                });

            modelBuilder.Entity("Kakeibo.Domain.Entities.SubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Kakeibo.Domain.Entities.TransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Memo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Kakeibo.Domain.Entities.TransactionEntity", b =>
                {
                    b.HasOne("Kakeibo.Domain.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
